# Settings that the LAMMPS build will import when this package library is used
#
# settings for ADIOS

ADIOS_DIR = /opt/adios
adios_SYSINC = -I${ADIOS_DIR}/include
adios_SYSLIB = `${ADIOS_DIR}/bin/adios_config -l`
adios_SYSPATH =

